# Site settings
title:       "Theranos (Official)" #the title of your course
email:       ramneeknarayan0@icloud.com #your personal email for contact, edit as you wish
author:      'Elizabeth Holmes & Ramneek Narayan' #change to your name, e.g. bill stevens
description: "The offical site for Theranos"
url:         "https://writerthethinker1.github.io" #change the url to
# your 'https://github_username.github.io'
baseurl:     "/Official-Theranos/" #change the base url to your class title (name of git repo), e.g. /relax_101/ or /math123/


date_format: "%b %-d, %Y"

# easy links to reference them in any post or article, just use [name of link]({{ site.[link] | relative_url }})

Theranos-images: 'Theranos-images' #feel free to add custom image paths, like images/stats, images/discussion_things, images/coding, images/finals, images/your_scores/midterm1, images/practice_problems and so on...
# had to rename or append _link at the end of the names to make sure the entire collection wasn't referenced...

# # Google services
# google_verification:
# # Use either direct GA implementation or set up GTM account
# # - using both will skew your data (leave blank to not use at all)
# google_analytics:
# google_tag_manager:
# # Bing services
# bing_verification:

# # Optional features
# animated:             false
# show_related_posts:   false
# show_post_footers:    false
# show_social_icons:    false
# ajaxify_contact_form: false
# #enable_mathjax: true
# extended_fonts: false
# enable_anchorjs: false
# # Preview image for social media aka og:image and twitter:image
# post_preview_image: false

collections:
  Theranos-practice:
    output: true
  Theranos-discussions:
    output: true
  Theranos-markdown_notes:
    output: true
  Theranos-musings:
    output: true

# for static files (things like articles, books, extra_things, week_Theranos_notes)

#if you don't want any folders or don't use them, comment out them here!, you can also make your own static file collections too.
defaults:
  - scope:
      path: "Theranos-notes_upload/Theranos-books"
    values:
      Theranos-book: true #all files in the books folder have the 'book' frontmatter as true, as if
  - scope:
      path: "Theranos-notes_upload/Theranos-articles"
    values:
      Theranos-article: true
  - scope:
      path: "Theranos-notes_upload/Theranos-extras"
    values:
      Theranos-extra: true
  - scope:
      path: "Theranos-notes_upload/Theranos-notes"
    values:
      Theranos-notes: true
  - scope:
      path: "Theranos-notes_upload/Theranos-discussion_stuff"
    values:
      Theranos-discussion_stuff: true
  - scope:
      path: "Theranos-notes_upload/Theranos-exam_solutions"
    values:
      Theranos-exam_solutions: true
  - scope:
      path: "Theranos-notes_upload/Theranos-practice_solutions"
    values:
      Theranos-practice_solutions: true
  - scope:
      path: "Theranos-notes_upload/Theranos-study_guides"
    values:
      Theranos-study_guides: true
  - scope:
      path: "Theranos-notes_upload/Theranos-labs"
    values:
      Theranos-labs: true
  - scope:
      path: "Theranos-notes_upload/Theranos-coding"
    values:
      Theranos-coding: true


# Facebook Page integration
# (for instant articles and other stuff)
#fb_page: false
#fb_page_id:

# Disqus post comments
# (leave blank to disable Disqus)
#disqus_shortname:

# Facebook Comments plugin
# (leave blank to disable Facebook Comments, otherwise set it to true)
#facebook_comments:
#facebook_appid:
#facebook_comments_number: 10

# Social icons
#github_username:
#reddit_username:
#bitbucket_username:
#stackoverflow_id:
#twitter_username:
#skype_username:
#steam_nickname:
#google_plus_id:
#linkedin_username:
#angellist_username:
#medium_id:
#bitcoin_url:
#paypal_url:
#flattr_button:
#telegram_username:
#vk_id:

# Post sharing icons
#show_sharing_icons: false
# Change to 'true' to enable individual icons
#share_facebook: false
#share_twitter: false
#share_googleplus: false
#shareedin: false
#share_digg: false
#share_tumblr: false
#share_reddit: false
#share_stumbleupon: false
#share_hackernews: false

text:
  pagination:
    newer: 'Newer'
    older: 'Older'
  # share_buttons:
  #   text:         'Share this post!'
  #   facebook:     'Share on Facebook'
  #   twitter:      'Share on Twitter'
  #   googleplus:   'Share on Google+'
  #   linkedin:     'Share on LinkedIn'
  #   digg:         'Share on Digg'
  #   tumblr:       'Share on Tumblr'
  #   reddit:       'Share on Reddit'
  #   stumbleupon:  'Share on StumbleUpon'
  #   hackernews:   'Share on Hacker News'
  # post:
  #   updated:        'Updated'
  #   minute_read:    'minute read'
  #   related_posts:  'Related Posts'
  # index:
  #   coming_soon: 'Coming soon...'
  # contact:
  #   email:    'Email Address'
  #   content:  'What would you like to say?'
  #   subject:  'New submission!'
  #   submit:   'Say Hello'
  #   ajax:
  #     sending:  'sending..'
  #     sent:     'Message sent!'
  #     error:    'Error!'
  # thanks: 'Thanks for contacting us. We will reply as soon as possible.'
  # og_locale: 'en_US'

# Build settings
markdown:     kramdown
highlighter: rouge
redcarpet:
  extensions: ['smart', 'tables', 'with_toc_data']
permalink:    pretty
paginate:     4
sass:
  style: compressed
plugins:
  - jekyll-paginate
  - jekyll-sitemap
# https://github.com/jekyll/jekyll/issues/2938
exclude:
  - Gemfile
  - Gemfile.lock
  - vendor
